[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
via_ir = true

# Monad Mainnet
[rpc_endpoints]
monad = "${MONAD_RPC_URL}"
localhost = "http://localhost:8545"

[etherscan]
monad = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.monad.xyz/api" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.ci]
fuzz = { runs = 1000 }
invariant = { runs = 100 }
